-- 1
SELECT * FROM EMPLOYEES;
SELECT
	FIRST_NAME,
	LOWER(FIRST_NAME)
FROM EMPLOYEES;
-- 2
SELECT
	FIRST_NAME,
	UPPER(SUBSTR(FIRST_NAME,1,1)),
	INITCAP(lower(FIRST_NAME))
FROM EMPLOYEES;
-- 3 알파벳 1개당 1바이트 사용. 따라서 아래 결과 무차별
SELECT
	FIRST_NAME,
	LENGTH(FIRST_NAME),
	LENGTHB(FIRST_NAME),
	VSIZE(FIRST_NAME)
FROM EMPLOYEES;
-- 4 <- instr에서 뒤에 2개 지정 안 하면 디폴트가 1,1
SELECT
	FIRST_NAME,
	instr(FIRST_NAME,'A',1,1),
	instr(FIRST_NAME,'a',1,1),
	instr(FIRST_NAME,'A'),
	instr(FIRST_NAME,'a')
FROM EMPLOYEES;
-- 5 <- 아래 3개는 모두 같음
SELECT *
FROM EMPLOYEES
WHERE SUBSTR(FIRST_NAME,3,1)='r'
;

SELECT *
FROM EMPLOYEES
WHERE INSTR(FIRST_NAME,'r')=3
;

SELECT *
FROM EMPLOYEES
WHERE FIRST_NAME LIKE ('__r%')
;
-- 6 <- 위 아래 결과 동일. length() 함수의 유용성에 유의!
--     사원이름끝자리 'n'인 것 찾기
SELECT *
FROM EMPLOYEES
WHERE SUBSTR(FIRST_NAME,-1,1)='n'
;
SELECT *
FROM EMPLOYEES
WHERE SUBSTR(FIRST_NAME,LENGTH(FIRST_NAME),1)='n'
;

-- 7 <- 07년도 입사 찾기 (3번째 정규표현식도 유의)
SELECT
	FIRST_NAME,
	SALARY
FROM EMPLOYEES
WHERE SUBSTR(HIRE_DATE,3,2)=07;

SELECT
	FIRST_NAME,
	SALARY
FROM EMPLOYEES
WHERE TO_CHAR(HIRE_DATE,'yy')=07;

SELECT
	FIRST_NAME,
	SALARY
FROM EMPLOYEES
WHERE REGEXP_LIKE(HIRE_DATE,'^..07.*');

-- 8
SELECT
	FIRST_NAME,
	UPPER(SUBSTR(FIRST_NAME,1,1))
FROM EMPLOYEES
WHERE LENGTH(FIRST_NAME)=5;

-- 9
SELECT
	FIRST_NAME,
	TO_CHAR(HIRE_DATE,'yyyy-mm-dd') 입사일,
	TO_CHAR(TRUNC(SYSDATE-HIRE_DATE),'9,999')||' 일' 경과일
FROM EMPLOYEES;
-- 10
SELECT
	FIRST_NAME,
	TO_CHAR(HIRE_DATE,'yyyy-mm-dd') 입사일,
	TRUNC((SYSDATE-HIRE_DATE)/30) 경과월,
	TRUNC((SYSDATE-HIRE_DATE)/30.5) 경과월, -- <- 30.5가 그나마 30보다 정확
	TRUNC(MONTHS_BETWEEN(SYSDATE,HIRE_DATE)) 경과월 -- <- 이게 가장 정확
FROM EMPLOYEES;
-- 11
SELECT
	FIRST_NAME,
	TO_CHAR(HIRE_DATE,'yyyy-mm-dd') 입사일,
	TO_CHAR(NEXT_DAY(HIRE_DATE,'일요일'),'yyyy-mm-dd') 입사후첫일요일
FROM EMPLOYEES;
-- 12 입사후6개월지난날짜 바로다음 일요일
SELECT
	FIRST_NAME,
	TO_CHAR(HIRE_DATE,'yyyy-mm-dd') 입사일,
	NEXT_DAY(ADD_MONTHS(HIRE_DATE,6),'일요일')
FROM EMPLOYEES;
-- 13
SELECT
	SYSDATE,
	TO_CHAR(SYSDATE,'yy')||'년 '||TO_CHAR(SYSDATE,'mon')||TO_CHAR(SYSDATE,'dd')||'일',
	TO_CHAR(SYSDATE,'yy"년 "mm"월 "dd"일"') -- <- 이거 유의!
FROM dual;
-- 14
SELECT
	SYSDATE,
	TO_CHAR(SYSDATE,'hh24"시 "mi"분 "ss"초"') "1",
	TO_CHAR(SYSDATE,'am hh"시 "mi"분 "ss"초"') "2",
	TO_CHAR(SYSDATE,'am hh24"시 "mi"분 "ss"초"') "3"
FROM dual;
-- 15 확인 필요
SELECT
	MONTHS_BETWEEN('2019-12-31',TO_CHAR(SYSDATE,'yyyy-mm-dd')) "1",
	MONTHS_BETWEEN('2019-12-31',SYSDATE) "2",
	TRUNC(TO_DATE('2019-12-31')-SYSDATE)||'일' 월말까지남은일수
FROM dual;
-- 16
SELECT
	HIRE_DATE,
	TO_CHAR(HIRE_DATE,'yyyy') 입사년도,
	TO_CHAR(HIRE_DATE,'mm') 입사월,
	SUBSTR(HIRE_DATE,1,4) 입사년도,
	SUBSTR(HIRE_DATE,6,2) 입사월,
	TO_CHAR(HIRE_DATE,'yyyy"년 "mm"월 "') 입사년월
FROM EMPLOYEES;
-- 17 입사월이 9월인 사람들...
SELECT HIRE_DATE
FROM EMPLOYEES
WHERE TO_CHAR(HIRE_DATE,'mm')='09';
SELECT HIRE_DATE
FROM EMPLOYEES
WHERE SUBSTR(HIRE_DATE,6,2)='09';
SELECT HIRE_DATE
FROM EMPLOYEES
WHERE INSTR(HIRE_DATE,'09')=6;
WHERE SUBSTR(HIRE_DATE,6,2)='09';
SELECT HIRE_DATE
FROM EMPLOYEES
WHERE INSTR(HIRE_DATE,'09',6)=6; -- 요것 유의. 바로 위보다 더 정교함. 2009년과 같이 앞에 09 있는 risk 헷징
-- 18
SELECT
	HIRE_DATE,
	TO_CHAR(HIRE_DATE,'yyyy-mm-dd day')
FROM EMPLOYEES;
-- 19 원화는 l(엘):localized currency symbol?? // trim 효과성 확인
SELECT 
	SALARY,
	TO_CHAR(SALARY,'l999,999,999') 원화기준1,
	trim(TO_CHAR(SALARY,'l999,999,999')) 원화기준2
FROM EMPLOYEES;
-- 20 컴마 쓸 수 있다는 것에 유의
SELECT
	SALARY,
	TO_CHAR(SALARY,'l0000000000'),
	TO_CHAR(SALARY,'l0,000,000,000')
FROM EMPLOYEES;
-- 21
SELECT
	trunc(MONTHS_BETWEEN(SYSDATE,HIRE_DATE))
FROM EMPLOYEES;
-- 22
SELECT
	ADD_MONTHS(HIRE_DATE,4)
FROM EMPLOYEES;
-- 23
SELECT
	LAST_DAY(HIRE_DATE)
FROM EMPLOYEES;

